format_version: v1.0
type: UniqueComponent
attributes: {id: usart0}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart0, value: '81'}
  - type: Comment
    attributes: {id: USART_BAUD_WARNING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: USART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart0, value: '150000000'}
  - type: KeyValueSet
    attributes: {id: USART_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart0, value: '0'}
  - type: Integer
    attributes: {id: USART_SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usart0, value: '150'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: USART0_SPI}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectCapability
    attributes: {id: USART0_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: bluetooth_bm71}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: USART PLIB}
- type: ElementPosition
  attributes: {x: '760', y: '131', id: usart0}
